# Generated by Django 4.2 on 2025-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar_default/avatar_default.jpg', null=True, upload_to='avatar'),
        ),
    ]
